### ISSUE TITLE
Arduino IDE reports "no device found on ttymxc3".

### ISSUE THREAD

**Issue by patrykk** [patrykk/linux-udoo#8]
Arduino IDE reports "no device found on ttymxc3" during flashing. 
We don't have access to SAM processor

**Comment by spinxz** [comment]
Is there another reason for this to happen? I got the same problem with commit 77d16.
I activated gpio 0 and 117 as suggested by you.

**Comment by patrykk** [comment]
Please check your dtb version too.
I have tested last kernel:

echo 0 > /sys/class/gpio/export; echo 117 > /sys/class/gpio/export
[root@h4 ]# /usr/src/arduino-1.5.4/arduino 
/home/src/arduino-1.5.4/hardware/tools/arm-none-eabi/bin/../lib/gcc/arm-none-eabi/4.6.2/../../../../arm-none-eabi/lib/thumb/libc.a(lib_a-sbrkr.o): In function `_sbrk_r':
sbrkr.c:(.text._sbrk_r+0xc): warning: undefined reference to`_sbrk'

Sketch uses 12,012 bytes (2%) of program storage space. Maximum is 524,288 bytes.

Inner erase and reset routine:  successiful!!
Erase flash
Write 14192 bytes to flash

[                              ] 0% (0/56 pages)
[=====                         ] 17% (10/56 pages)
[==========                    ] 35% (20/56 pages)
[================              ] 53% (30/56 pages)
[=====================         ] 71% (40/56 pages)
[==========================    ] 89% (50/56 pages)
[==============================] 100% (56/56 pages)
Verify 14192 bytes of flash

[                              ] 0% (0/56 pages)
[=====                         ] 17% (10/56 pages)
[==========                    ] 35% (20/56 pages)
[================              ] 53% (30/56 pages)
[=====================         ] 71% (40/56 pages)
[==========================    ] 89% (50/56 pages)
[==============================] 100% (56/56 pages)
Verify successful
Set boot flash true
CPU reset.

**Comment by patrykk** [comment]
Did you make it from user root or did you check dev privileges?

**Comment by spinxz** [comment]
Hi.
I am running your latest kernel 4.0.0.
I changed the dev privilages but ran the IDE from root anyway:

```
$ sudo su

Load: 0.01, 0.04, 0.05 - Memory: 728Mb

root@udoo:/# echo 0 > /sys/class/gpio/export 
root@udoo:/# echo 117 > /sys/class/gpio/export 
root@udoo:/# /opt/arduino0158/arduino 
Xlib:  extension "RANDR" missing on display ":1".

Sketch uses 10,484 bytes (1%) of program storage space. Maximum is 524,288 bytes.
No device found on ttymxc3
```

DTB files:

```
/boot/dtb$ ls -la
total 104
drwxr-xr-x 2 root root  4096 Jun 16 11:16 .
drwxr-xr-x 4 root root  4096 Jun 16 11:16 ..
-rw-r--r-- 1 root root 31962 Jun 14 19:49 imx6dl-udoo.dtb
-rw-r--r-- 1 root root 34604 Jun 14 19:49 imx6q-udoo.dtb
-rw-r--r-- 1 root root 26212 Jun 14 19:49 imx6sl-evk.dtb
```

I used Igor's compile scripts and built a dtb deb package which is installed.

boot.cmd:

```
setenv bootargs root=/dev/mmcblk0p1 rootfstype=ext4 rootwait console=ttymxc1 video=mxcfb0:dev=hdmi,1920x1080M@60,if=RGB24,bpp=32 ahci_imx.hotplug=1 quiet loglevel=1 
ext2load mmc 0 0x18000000 /boot/dtb/${fdt_file}
ext2load mmc 0 0x12000000 /boot/zImage
bootz 0x12000000 - 0x18000000
```

I adapted the makefile for this in <kernel_src>/arch/arm/boot/dts/Makefile so that the section for the imx6q becomes

```
dtb-$(CONFIG_SOC_IMX6Q) += \
       imx6dl-udoo.dtb \
       imx6q-udoo.dtb
```

Am I missing something?

**Comment by patrykk** [comment]
Could you compile with config : http://kowalczyk.ws/imx/kernel/4.0/config and make imx6q-udoo.dtb via command "make imx6q-udoo.dtb" from root directory of kernel source code (without any modifications)

**Comment by spinxz** [comment]
Hi. Sorry for the looong delay. I have been trying to fix this problem but could not find the cause. I used your most recent kernel and the imx6q-udoo.dtb is loaded correctly by uboot.

However, I think the problem is somewhere else and not in the kernel. I can use the serial monitor in the Arduino IDE (using udoo's 1.5.8 armhf version with bossac file jasmx) and it does not complain when I send something. So I guess the problem is related to the Arudino IDE or the bossac file.
